# Generated by Django 2.1.4 on 2018-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181205_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='product',
            name='productnumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='prueba', max_length=250),
        ),
    ]
