# Generated by Django 2.1.4 on 2018-12-05 18:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_user_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productnumber',
            new_name='product_number',
        ),
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
